// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nssynxdfjqefujjieitk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zc3lueGRmanFlZnVqamllaXRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDI5NzUsImV4cCI6MjA2NTQ3ODk3NX0.CT0CVNFiGgDxz-rIbCtXq7vfjt6igNNkoxwhDgKUe9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);